---
output:
  html_document: default
  pdf_document: default
---


''''{r}
getwd()
list.files()
pf = read.csv("E:\\Projects\\R\\data\\pseudo_facebook.tsv", sep = '\t')
names(pf)
  

***

```{r Omitting NA Values}

qplot(x = friend_count, data = subset(pf, !is.na(gender)), binwidth = 10) +
  scale_x_continuous(limits = c(0, 1000),
                     breaks = seq(0, 1000, 50))+ facet_wrap(~gender)

```

***

### Statistics 'by' Gender
Notes:

```{r Statistics \'by\' Gender}
table(pf$gender)


by(pf$friend_count,pf$gender,summary)

```



***

### Tenure
Notes:

```{r Tenure}

qplot(x = tenure/365, data = pf, binwidth = .25)+
  geom_histogram(binwidth = .25, color = 'black', fill = '#099DD9')

```

***

#### How would you create a histogram of tenure by year?

```{r Tenure Histogram by Year}
qplot(x = tenure/365, data = pf, binwidth = .25)+
  geom_histogram(binwidth = .25, color = 'black', fill = '#099DD9')
```

***

### Labeling Plots
Notes:

```{r Labeling Plots}
qplot(x = tenure/365, data = pf,xlab = "Number of years using facebook", ylab = "Number of users in sample")


```

***

### User Ages
Notes:

```{r User Ages}
qplot(x = age, data = pf, binwidth = 5,xlab = "Age of facebook users", ylab = "Number of users in sample")+
  geom_histogram(binwidth = 5, color = 'black', fill = '#099DD9')+
  scale_x_continuous(breaks = seq(0, 113, 5))

#set x from 0 -> 100 and incrment  by 5
```



### Add a Scaling Layer
Notes:

```{r Add a Scaling Layer}
qplot(x = age, data = pf, binwidth = .1,xlab = "Age of facebook users", ylab = "Number of users in sample") +
  geom_histogram(binwidth = .1, color = 'black', fill = '#099DD9') +
  scale_x_continuous(breaks = seq(0, 113, 5)) +
  scale_x_sqrt(breaks = seq(0, 113, 5))
  


```

***


### Frequency Polygons

```{r Frequency Polygons}

qplot(x = friend_count,
      data = subset(pf,!is.na(gender)),
      geom = "freqpoly",color='gender'
     ) +
facet_wrap(~gender)

qplot(x = friend_count, y= ..count../sum(..count..),ylab = "count" ,data = subset(pf, !is.na(gender)),
      binwidth= 10, geom = 'freqpoly', color = gender)  +
scale_x_continuous(lim = c(0,1000),breaks = seq(0,1000,50))
```



### Box Plots
Notes:

```{r Box Plots}

qplot(x = gender, y = friend_count, 
      data = subset(pf, !is.na(gender)), 
      geom='boxplot', ylim=c(0,1000))

qplot(x = gender, y = friend_count,
      data = subset(pf, !is.na(gender)),
      geom = 'boxplot'
      )+
      coord_cartesian(ylim = c(0,1000))



```

have an html
page of this lesson, your answers, and your notes!